import { Difficulty, PoseCategory, YogaPose } from './types';

export const YOGA_POSES: YogaPose[] = [
  {
    id: 'tadasana',
    nameEn: 'Mountain Pose',
    nameHi: 'Tadasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.STANDING,
    description: 'The foundation of all standing poses, Tadasana improves posture and strengthens legs.',
    benefits: ['Improves posture', 'Strengthens thighs, knees, and ankles', 'Firms abdomen and buttocks'],
    precautions: ['Headache', 'Insomnia', 'Low blood pressure'],
    duration: '30-60 seconds',
    breathing: 'Steady and deep abdominal breathing',
    commonMistakes: ['Locking knees', 'Holding breath', 'Uneven weight distribution'],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400',
    idealAngles: { shoulder: 180, hip: 180, knee: 180 }
  },
  {
    id: 'vrikshasana',
    nameEn: 'Tree Pose',
    nameHi: 'Vrikshasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.BALANCING,
    description: 'A balancing pose that replicates the graceful, steady stance of a tree.',
    benefits: ['Improves balance', 'Strengthens spine', 'Tones leg muscles'],
    precautions: ['Recent leg injury', 'Migraine'],
    duration: '1 minute per leg',
    breathing: 'Focus on inhalation as you reach up',
    commonMistakes: ['Placing foot on knee joint', 'Tilting pelvis', 'Rounding shoulders'],
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=400',
    idealAngles: { knee: 45, hip: 90 }
  },
  {
    id: 'virabhadrasana',
    nameEn: 'Warrior II',
    nameHi: 'Virabhadrasana II',
    difficulty: Difficulty.INTERMEDIATE,
    category: PoseCategory.STANDING,
    description: 'Builds stamina, focus, and strength in the entire body.',
    benefits: ['Stretches hips and groin', 'Increases lung capacity', 'Stimulates abdominal organs'],
    precautions: ['High blood pressure', 'Neck problems'],
    duration: '30-60 seconds',
    breathing: 'Exhale as you bend the knee',
    commonMistakes: ['Knee passing ankle', 'Leaning torso forward', 'Dropping back arm'],
    image: 'https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&q=80&w=400',
    idealAngles: { frontKnee: 90, rearLeg: 180, arms: 180 }
  },
  {
    id: 'bhujangasana',
    nameEn: 'Cobra Pose',
    nameHi: 'Bhujangasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.LYING,
    description: 'A reclining back-bending pose that strengthens the spine and opens the chest.',
    benefits: ['Strengthens the spine', 'Stretches chest and lungs', 'Stimulates abdominal organs'],
    precautions: ['Back injury', 'Carpal tunnel syndrome', 'Pregnancy'],
    duration: '15-30 seconds',
    breathing: 'Inhale while lifting the chest',
    commonMistakes: ['Overextending the neck', 'Locking elbows', 'Tensing shoulders'],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400&q=2',
    idealAngles: { shoulder: 160, hip: 150 }
  },
  {
    id: 'adho-mukha-svanasana',
    nameEn: 'Downward Dog',
    nameHi: 'Adho Mukha Svanasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.STANDING,
    description: 'One of the most widely recognized poses, it energizes and rejuvenates the entire body.',
    benefits: ['Calms the brain', 'Energizes the body', 'Stretches shoulders and hamstrings'],
    precautions: ['Carpal tunnel syndrome', 'High blood pressure'],
    duration: '1-3 minutes',
    breathing: 'Long, deep exhales while pushing hips up',
    commonMistakes: ['Rounding the back', 'Weight too forward on hands', 'Shrugging shoulders'],
    image: 'https://images.unsplash.com/photo-1588282322631-404868bc5041?auto=format&fit=crop&q=80&w=400',
    idealAngles: { shoulder: 180, hip: 90, knee: 180 }
  },
  {
    id: 'balasana',
    nameEn: 'Child\'s Pose',
    nameHi: 'Balasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.SITTING,
    description: 'A resting pose that provides a sense of calm and stability.',
    benefits: ['Gently stretches hips', 'Calms the mind', 'Relieves back and neck pain'],
    precautions: ['Knee injury', 'Pregnancy'],
    duration: '1-5 minutes',
    breathing: 'Breath into the back of the ribs',
    commonMistakes: ['Holding tension in shoulders', 'Lifting hips off heels'],
    image: 'https://images.unsplash.com/photo-1510894347713-fc3ad6cb0d4d?auto=format&fit=crop&q=80&w=400',
    idealAngles: { knee: 30, hip: 30 }
  },
  {
    id: 'trikonasana',
    nameEn: 'Triangle Pose',
    nameHi: 'Trikonasana',
    difficulty: Difficulty.INTERMEDIATE,
    category: PoseCategory.STANDING,
    description: 'A foundational pose that creates space in the body and improves alignment.',
    benefits: ['Strengthens legs and core', 'Stretches hips and spine', 'Improves digestion'],
    precautions: ['Low blood pressure', 'Neck injuries'],
    duration: '30 seconds per side',
    breathing: 'Deep, expansive chest breathing',
    commonMistakes: ['Collapsing the side body', 'Locking the front knee', 'Looking down'],
    image: 'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?auto=format&fit=crop&q=80&w=400',
    idealAngles: { hip: 90, knee: 180, shoulder: 180 }
  },
  {
    id: 'phalakasana',
    nameEn: 'Plank Pose',
    nameHi: 'Phalakasana',
    difficulty: Difficulty.BEGINNER,
    category: PoseCategory.BALANCING,
    description: 'A core-strengthening pose that builds stability and arm strength.',
    benefits: ['Core strength', 'Arm and wrist stability', 'Improves posture'],
    precautions: ['Carpal tunnel syndrome', 'Wrist pain'],
    duration: '30-60 seconds',
    breathing: 'Steady, rhythmic breaths',
    commonMistakes: ['Sagging hips', 'Hiking hips too high', 'Holding breath'],
    image: 'https://images.unsplash.com/photo-1566241142559-40e1bfc26ddc?auto=format&fit=crop&q=80&w=400',
    idealAngles: { shoulder: 90, hip: 180, knee: 180 }
  },
  {
    id: 'ustrasana',
    nameEn: 'Camel Pose',
    nameHi: 'Ustrasana',
    difficulty: Difficulty.INTERMEDIATE,
    category: PoseCategory.SITTING,
    description: 'A deep backbend that opens the heart center and improves flexibility.',
    benefits: ['Stretches entire front of body', 'Strengthens back muscles', 'Improves posture'],
    precautions: ['Back or neck injury', 'High or low blood pressure'],
    duration: '30-60 seconds',
    breathing: 'Avoid holding breath while bending back',
    commonMistakes: ['Crunching the lower back', 'Dropping the head too far back', 'Hips shifting back'],
    image: 'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?auto=format&fit=crop&q=80&w=400',
    idealAngles: { knee: 90, hip: 180, shoulder: 45 }
  }
];

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'AI Trainer', path: '/trainer' },
  { name: 'Library', path: '/library' },
  { name: 'Dashboard', path: '/dashboard' },
  { name: 'Meditation', path: '/meditation' }
];
